[theme]
primaryColor = "#FFFFFF"
backgroundColor = "#080808"
secondaryBackgroundColor = "#000000"
textColor = "#FFFFFF"
font = "Chomsky"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false 